@startuml
start
:Home Screen;
if (Choose Order?) then (yes)
  :Add Sandwich;
  :Add Drink;
  :Add Chips;
  :Checkout;
  :Confirm & Pay;
  :Print/Email Receipt;
else
  if (View Past Orders?) then (yes)
    :Show Order History;
  endif
endif
stop
@enduml

